sudo: required
language: julia
os:
    - osx
    - linux
julia:
    - 0.3
    - 0.4
    - nightly

notifications:
    email: false

before_install:
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then sudo apt-get install libpcre3-dev gfortran; fi
#  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then brew update; fi
#  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then brew outdated gcc || brew install gcc; fi

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Dierckx")'
  - julia -e 'Pkg.test("Dierckx"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Dierckx")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'