language: julia
os:
    - osx
    - linux
julia:
    - 0.3
    - 0.4
    - nightly

notifications:
    email: false

before_install:
  - apt-get update -qq
  - apt-get install libpcre3-dev gfortran

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Dierckx")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Sundials"); Pkg.test("Sundials"; coverage=true)';
  - julia -e 'Pkg.test("Dierckx"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Dierckx")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'